controllers:
    resource: '../../src/Controller/'
    type: annotation
    # prefix: /{_locale}
    prefix: /
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'
